#!/usr/bin/env python

import argparse

def main():
    p = argparse.ArgumentParser(description="useful-tool does useful things")
    p.add_argument("--output", help="input file")
    p.add_argument("--input", help="output file")
    p.add_argument(
        "--do-it-efficiently",
        action="store_true",
        help="enable effecient mode"
    )
    p.parse_args()
    print("Now shell completion works!")

if __name__ == "__main__":
    main()
